development: &development
  adapter: mysql
  database: comatoast_development
  username: twg
  password: twgRulez
  host: 127.0.0.1
  encoding: UTF8

staging:
  <<: *development
  database: comatoast_staging

test:
  <<: *development
  database: comatoast_test

production:
  <<: *development
  database: comatoast_production